version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chatstream-db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - chatstream-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatstream-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - chatstream-network
    restart: unless-stopped
    volumes:
      - ./backend/appsettings.Production.json:/app/appsettings.Production.json

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatstream-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chatstream-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  chatstream-network:
    driver: bridge